scripts: add_license: Explicitly specify encoding
* Some system have different default encoding,
  causing traceback

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\YeetAI\scripts\add_license.py", line 54, in <module>
    if add_license_header(file):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\YeetAI\scripts\add_license.py", line 45, in add_license_header
    content = f.read()
              ^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1428: character maps to <undefined>